### ISSUE TITLE
Compatibility Questions

### ISSUE THREAD

**Issue by danielnovello-pf** [erikng/hello#1]
macOS version 11.4
Xcode version: 12.5

_The project at '/hello-main/hello.xcodeproj' cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode._

Editing /hello-main/hello.xcodeproj/project.pbxproj (`objectVersion`) manually from `55` to `54`, allows me to open it, but some of the Beta tools and commands are not available.
A few `Cannot find 'AsyncImage' in scope` errors and `Cannot infer contextual base in reference to member 'link'` errors.
https://developer.apple.com/documentation/swiftui/asyncimage?changes=_6 (AsyncImage view 10.12+ only?)

Thus the macOS 10.12+ beta compatibility question.

**Comment by erikng** [comment]
Only Xcode 13 supports Swift 5.5, which is what this  application is written in. The target OS is macOS 11 and higher. I use several conditionals to use new features in macOS 12 and fallback to old methods in macOS 11.
