### ISSUE TITLE
[SwiftUI] No symbol named 'gear.circle' found 

### ISSUE THREAD

**Issue by trekkim** [erikng/hello#5]
Hi Erik,

i discover this issue on Big Sur  during my testing Hello 0.2.2 . 
<img width="161" alt="Screenshot 2021-07-22 at 17 45 29" src="https://user-images.githubusercontent.com/6920257/126677378-a6d10083-ed39-41dc-9539-1e415d3efa80.png">

2021-07-22 18:46:22.523077+0200 hello[40018:764438] [SwiftUI] No symbol named 'gear.circle' found in system symbol set
2021-07-22 18:46:22.554990+0200 hello[40018:764438] [SwiftUI] No symbol named 'gear.circle' found in system symbol set
2021-07-22 18:46:25.067170+0200 hello[40018:764438] [SwiftUI] No symbol named 'gear.circle' found in system symbol set
2021-07-22 18:46:25.166747+0200 hello[40018:764438] [SwiftUI] No symbol named 'circle.dashed.inset.filled' found in system symbol set

**Comment by cdog2020** [comment]
Hi Trekkim,

While testing on Big Sur you will want to make sure that the SF Symbol is compatible with the OS you're testing on.  In this case, the image listed in Erik's example is from the SF Beta and is compatible with Monterey.  Alternatively, in my testing on Big Sur I changed this to `"welcomeScreenItem1SymbolName": "gear"`

**Comment by trekkim** [comment]
Hi  cdog2020,

can you please share here where exactly cause i changed, but still  No Symbol error.
<img width="324" alt="Screenshot 2021-07-22 at 19 50 36" src="https://user-images.githubusercontent.com/6920257/126685481-6e7a8b91-bd51-4d3e-8dbd-13219435f8bd.png">
<img width="224" alt="Screenshot 2021-07-22 at 19 51 14" src="https://user-images.githubusercontent.com/6920257/126685548-89d6e5be-90c7-4f3d-ab38-70e2305236e0.png">


thx

**Comment by cdog2020** [comment]
Hey Trekkim,

It looks to me like you're editing the project itself.  I was speaking to changing that in the JSON for the already built version of hello.  I have not edited anything in the swift project in testing.

**Comment by trekkim** [comment]
Ok, yeap i wanna  understand little bit  how it is written ;-)

**Comment by trekkim** [comment]
I sorted 2021-07-22 18:46:25.166747+0200 hello[40018:764438] [SwiftUI] No symbol named 'circle.dashed.inset.filled' found in 

just changed circle.dashed.inset.filled to circle.dashed.inset.fill :-)

**Comment by erikng** [comment]
hello should do something like 

`Image(systemName: symbolName) ?? Image(systemName: questionmark.square.fill)` to handle this.

**Comment by natewalck** [comment]
Have a solution for this in #8, but it isn't as nice as your one liner (I couldn't get it to work as swift is a lot of lolwut at times :D ).
